/* ═══════════════════════════════════════════════════════════════════
   The legacy system: a B2B payments schema on SQL Server 2022

   Every type in here is chosen because it breaks something on the way
   to PostgreSQL. The comments mark each trap so the FINDINGS writeup
   can be checked against what was intended, not just what happened.

   This is written the way a real legacy schema looks — IDENTITY keys,
   NVARCHAR everywhere, DATETIME2 with no timezone, and a stored
   procedure holding business logic that will have to be rewritten.
   ═══════════════════════════════════════════════════════════════════ */

IF DB_ID('payments') IS NULL
    CREATE DATABASE payments;
GO

USE payments;
GO

/* ─── merchants ───────────────────────────────────────────────────── */

IF OBJECT_ID('dbo.merchants', 'U') IS NOT NULL DROP TABLE dbo.merchants;
GO

CREATE TABLE dbo.merchants (
    -- TRAP 1: IDENTITY. Postgres equivalent is GENERATED BY DEFAULT AS
    -- IDENTITY, but the sequence does NOT reset itself after a bulk
    -- load. First insert after migration collides on the primary key
    -- unless the high-water mark is set explicitly.
    merchant_id     INT IDENTITY(1,1) PRIMARY KEY,

    -- TRAP 2: UNIQUEIDENTIFIER. SQL Server stores the first three
    -- fields little-endian; Postgres uuid is big-endian throughout.
    -- Moving the bytes directly scrambles it. The string form is safe.
    merchant_guid   UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID(),

    -- TRAP 3: NVARCHAR. Postgres is UTF-8 natively so text/varchar
    -- holds unicode without an N prefix. Seeded with non-ASCII names
    -- to prove the encoding survives.
    legal_name      NVARCHAR(200) NOT NULL,
    dba_name        NVARCHAR(200) NULL,

    -- TRAP 4: CHAR(4), fixed width. SQL Server and Postgres disagree
    -- subtly about trailing-space semantics in comparisons.
    mcc             CHAR(4) NOT NULL,

    -- TRAP 5: BIT. Becomes boolean. Every downstream query comparing
    -- to 0 or 1 breaks against true/false.
    is_active       BIT NOT NULL DEFAULT 1,

    -- TRAP 6: NVARCHAR status with MIXED CASE values, and SQL Server's
    -- default collation is case-INsensitive while Postgres is case
    -- sensitive. WHERE status = 'active' returns rows here and zero
    -- rows there. No error. This is the most dangerous trap in the file.
    onboarding_status NVARCHAR(20) NOT NULL,

    -- TRAP 7: DATETIME2 carries no timezone. Choosing timestamp vs
    -- timestamptz, and which zone to assume, moves dates by a day.
    created_at      DATETIME2(3) NOT NULL DEFAULT SYSUTCDATETIME(),
    updated_at      DATETIME2(3) NULL
);
GO

/* ─── transactions ────────────────────────────────────────────────── */

IF OBJECT_ID('dbo.transactions', 'U') IS NOT NULL DROP TABLE dbo.transactions;
GO

CREATE TABLE dbo.transactions (
    txn_id          BIGINT IDENTITY(1,1) PRIMARY KEY,
    merchant_id     INT NOT NULL,

    -- TRAP 8: MONEY. Scale of 4, and a range that does not map to any
    -- Postgres type by the same name. Postgres HAS a money type but it
    -- is locale-dependent and widely considered a mistake. The correct
    -- target is numeric(19,4). Anything involving float loses cents,
    -- which in payments is not a rounding detail, it is wrong.
    amount          MONEY NOT NULL,
    fee_amount      MONEY NOT NULL DEFAULT 0,

    currency        CHAR(3) NOT NULL DEFAULT 'USD',
    card_last4      CHAR(4) NULL,
    auth_code       VARCHAR(6) NULL,

    -- Mixed case again, on the column most likely to be filtered.
    txn_status      NVARCHAR(20) NOT NULL,

    captured_at     DATETIME2(3) NOT NULL,

    -- TRAP 9: deliberately nullable, and deliberately populated with
    -- NULLs. A conversion that silently turns NULL into '' or 0 shows
    -- up nowhere except a per-column NULL count.
    settled_at      DATETIME2(3) NULL,

    CONSTRAINT fk_txn_merchant FOREIGN KEY (merchant_id)
        REFERENCES dbo.merchants(merchant_id)
);
GO

-- TRAP 10: a CLUSTERED index. PostgreSQL has no equivalent. CLUSTER is
-- a one-time physical reorder that is not maintained on write, so the
-- performance characteristics after migration are genuinely different.
CREATE CLUSTERED INDEX ix_txn_captured ON dbo.transactions(captured_at);
GO

CREATE NONCLUSTERED INDEX ix_txn_merchant ON dbo.transactions(merchant_id);
GO

/* ─── batches ─────────────────────────────────────────────────────── */

IF OBJECT_ID('dbo.batches', 'U') IS NOT NULL DROP TABLE dbo.batches;
GO

CREATE TABLE dbo.batches (
    batch_id        INT IDENTITY(1,1) PRIMARY KEY,
    merchant_id     INT NOT NULL,

    -- DATE, not DATETIME. Maps cleanly, and is the control case that
    -- proves the timezone problem belongs to DATETIME2 and not to
    -- dates in general.
    batch_date      DATE NOT NULL,

    txn_count       INT NOT NULL,
    gross_amount    MONEY NOT NULL,
    batch_status    NVARCHAR(20) NOT NULL,

    CONSTRAINT fk_batch_merchant FOREIGN KEY (merchant_id)
        REFERENCES dbo.merchants(merchant_id)
);
GO

/* ─── settlements ─────────────────────────────────────────────────── */

IF OBJECT_ID('dbo.settlements', 'U') IS NOT NULL DROP TABLE dbo.settlements;
GO

CREATE TABLE dbo.settlements (
    settlement_id   INT IDENTITY(1,1) PRIMARY KEY,
    batch_id        INT NOT NULL,

    net_amount      MONEY NOT NULL,
    fee_amount      MONEY NOT NULL,

    -- TRAP 11: a computed column. Postgres generated columns exist but
    -- have stricter rules — they must be STORED and immutable.
    gross_amount    AS (net_amount + fee_amount) PERSISTED,

    settled_at      DATETIME2(3) NOT NULL,

    CONSTRAINT fk_settlement_batch FOREIGN KEY (batch_id)
        REFERENCES dbo.batches(batch_id)
);
GO

/* ─── the stored procedure ────────────────────────────────────────── */

/* TRAP 12: stored procedures do not convert. They get rewritten.

   T-SQL specifics in here that have no direct Postgres equivalent:
     - the procedure returns a result set implicitly; PL/pgSQL needs an
       explicit RETURNS TABLE
     - ISNULL is COALESCE
     - GETDATE / SYSUTCDATETIME is now()
     - DATEADD(day, -n, x) is x - INTERVAL 'n days'
     - the @parameter convention does not exist                         */

IF OBJECT_ID('dbo.sp_daily_settlement_summary', 'P') IS NOT NULL
    DROP PROCEDURE dbo.sp_daily_settlement_summary;
GO

CREATE PROCEDURE dbo.sp_daily_settlement_summary
    @days_back INT = 7
AS
BEGIN
    SET NOCOUNT ON;

    SELECT
        m.merchant_id,
        m.legal_name,
        CAST(t.captured_at AS DATE)          AS capture_date,
        COUNT(*)                             AS txn_count,
        SUM(t.amount)                        AS gross_amount,
        SUM(ISNULL(t.fee_amount, 0))         AS total_fees,
        SUM(t.amount - ISNULL(t.fee_amount, 0)) AS net_amount
    FROM dbo.transactions t
    INNER JOIN dbo.merchants m
        ON m.merchant_id = t.merchant_id
    WHERE t.captured_at >= DATEADD(day, -@days_back, SYSUTCDATETIME())
      AND t.txn_status = 'Captured'
    GROUP BY
        m.merchant_id,
        m.legal_name,
        CAST(t.captured_at AS DATE)
    ORDER BY
        capture_date DESC,
        gross_amount DESC;
END
GO

PRINT 'Schema created. 12 deliberate migration traps planted.';
GO
