/* ═══════════════════════════════════════════════════════════════════
   The target: the same payments schema on PostgreSQL 15

   This is the hand conversion. Every type decision is commented with
   the reasoning, because the reasoning is the deliverable — a tool can
   produce a schema, but it cannot tell you which of its choices would
   have quietly cost you money.

   Read alongside sqlserver/01_schema.sql. The trap numbers match.
   ═══════════════════════════════════════════════════════════════════ */

-- pg_cron is how scheduled jobs get rebuilt after the migration, because
-- RDS PostgreSQL has no SQL Server Agent. pg_stat_statements is how any
-- performance question gets answered with a number instead of a guess.
CREATE EXTENSION IF NOT EXISTS pg_stat_statements;
CREATE EXTENSION IF NOT EXISTS pg_cron;

/* ─── merchants ───────────────────────────────────────────────────── */

DROP TABLE IF EXISTS settlements CASCADE;
DROP TABLE IF EXISTS batches CASCADE;
DROP TABLE IF EXISTS transactions CASCADE;
DROP TABLE IF EXISTS merchants CASCADE;

CREATE TABLE merchants (
    -- TRAP 1 — IDENTITY.
    -- GENERATED BY DEFAULT (not ALWAYS) so the loader can supply explicit
    -- keys during migration. The catch: after a bulk load the sequence
    -- still sits at 1, so the first real insert collides on the primary
    -- key. The fix is setval() to the high-water mark, and it has to be
    -- done deliberately — nothing warns you.
    merchant_id       integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- TRAP 2 — UNIQUEIDENTIFIER.
    -- SQL Server stores the first three fields little-endian; Postgres
    -- uuid is big-endian throughout. Moving the bytes directly scrambles
    -- the value. Migrating via the STRING form is the safe path, and
    -- that is what the extract does.
    merchant_guid     uuid NOT NULL DEFAULT gen_random_uuid(),

    -- TRAP 3 — NVARCHAR.
    -- Postgres is UTF-8 natively, so text holds unicode with no N prefix
    -- and no separate wide type. text over varchar(n) deliberately:
    -- there is no performance difference in Postgres, and the length
    -- limit was a SQL Server storage artefact, not a business rule.
    legal_name        text NOT NULL,
    dba_name          text,

    -- TRAP 4 — CHAR(4).
    -- Kept as char(n) to preserve the trailing-space comparison semantics
    -- rather than silently changing them. In a real migration this is
    -- worth challenging: char(n) is almost always a mistake carried
    -- forward, but changing it during a migration means you can no longer
    -- tell a conversion bug from an intended fix.
    mcc               char(4) NOT NULL,

    -- TRAP 5 — BIT to boolean.
    -- Every downstream query comparing to 0 or 1 breaks against
    -- true/false. This is a code change, not a data change, and it will
    -- not be found by any row-count check.
    is_active         boolean NOT NULL DEFAULT true,

    -- TRAP 6 — the collation trap.
    -- SQL Server's default collation is case-INSENSITIVE. Postgres is
    -- case-SENSITIVE. WHERE status = 'active' returns different rows on
    -- each side, with no error.
    --
    -- Deliberately NOT normalised here. Papering over it during the load
    -- would hide the very thing the verification suite exists to catch.
    -- The real fix belongs in a follow-up migration, applied knowingly:
    -- either citext, or lower() with a functional index, or clean the
    -- data and add a CHECK constraint.
    onboarding_status text NOT NULL,

    -- TRAP 7 — DATETIME2 has no timezone.
    -- timestamptz, and the source is read as UTC explicitly. Choosing
    -- plain timestamp would have carried the ambiguity forward; guessing
    -- the offset wrong moves dates by a day, which the verification
    -- suite catches by comparing min and max on every date column.
    created_at        timestamptz NOT NULL DEFAULT now(),
    updated_at        timestamptz
);

/* ─── transactions ────────────────────────────────────────────────── */

CREATE TABLE transactions (
    txn_id        bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    merchant_id   integer NOT NULL,

    -- TRAP 8 — MONEY.
    -- Postgres HAS a type called money. Do not use it: it is
    -- locale-dependent, its scale is set by a server parameter, and it
    -- is widely considered a design mistake.
    --
    -- numeric(19,4) matches SQL Server MONEY's scale exactly and is
    -- arbitrary precision, so nothing rounds. The tempting shortcut is
    -- numeric(19,2) "because money has two decimals" — that silently
    -- truncates the 4-decimal fee amounts, and the loss only appears in
    -- a sum across 250,000 rows.
    --
    -- And never float. In payments a lost cent is not a rounding detail,
    -- it is a wrong number somebody has to reconcile later.
    amount        numeric(19,4) NOT NULL,
    fee_amount    numeric(19,4) NOT NULL DEFAULT 0,

    currency      char(3) NOT NULL DEFAULT 'USD',
    card_last4    char(4),
    auth_code     varchar(6),
    txn_status    text NOT NULL,

    captured_at   timestamptz NOT NULL,

    -- TRAP 9 — deliberately nullable and deliberately NULL in the data.
    -- A conversion that turns NULL into '' or 0 is invisible in a row
    -- count and invisible in a sum. Only a per-column NULL count finds it.
    settled_at    timestamptz,

    CONSTRAINT fk_txn_merchant FOREIGN KEY (merchant_id)
        REFERENCES merchants(merchant_id)
);

-- TRAP 10 — the clustered index has no equivalent.
--
-- In SQL Server a clustered index defines the physical row order and is
-- maintained on every write. Postgres has CLUSTER, but it is a one-time
-- reorder that decays as rows are updated, and it takes an exclusive
-- lock while it runs.
--
-- So this is a plain btree. The performance characteristics after
-- migration are genuinely different, and range scans over captured_at
-- are the queries to watch. This belongs in the findings, not in a
-- comment nobody reads.
CREATE INDEX ix_txn_captured ON transactions (captured_at);
CREATE INDEX ix_txn_merchant ON transactions (merchant_id);

/* ─── batches ─────────────────────────────────────────────────────── */

CREATE TABLE batches (
    batch_id     integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    merchant_id  integer NOT NULL,

    -- DATE maps cleanly and carries no timezone on either side. This is
    -- the control case: it proves the shift seen in DATETIME2 columns
    -- belongs to the type, not to the migration in general.
    batch_date   date NOT NULL,

    txn_count    integer NOT NULL,
    gross_amount numeric(19,4) NOT NULL,
    batch_status text NOT NULL,

    CONSTRAINT fk_batch_merchant FOREIGN KEY (merchant_id)
        REFERENCES merchants(merchant_id)
);

/* ─── settlements ─────────────────────────────────────────────────── */

CREATE TABLE settlements (
    settlement_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_id      integer NOT NULL,

    net_amount    numeric(19,4) NOT NULL,
    fee_amount    numeric(19,4) NOT NULL,

    -- TRAP 11 — computed column.
    -- SQL Server PERSISTED becomes GENERATED ALWAYS ... STORED. Postgres
    -- is stricter: the expression must be immutable, cannot reference
    -- other tables, and cannot be written to. Any computed column using
    -- GETDATE() or a user function will fail to convert and needs a
    -- trigger or a view instead.
    gross_amount  numeric(19,4) GENERATED ALWAYS AS (net_amount + fee_amount) STORED,

    settled_at    timestamptz NOT NULL,

    CONSTRAINT fk_settlement_batch FOREIGN KEY (batch_id)
        REFERENCES batches(batch_id)
);

/* ─── TRAP 12 — the stored procedure, rewritten ───────────────────── */

/* Not converted. Rewritten.

   What had to change:
     - T-SQL returns a result set implicitly; PL/pgSQL needs an explicit
       RETURNS TABLE and a RETURN QUERY
     - ISNULL          → COALESCE
     - SYSUTCDATETIME  → now()
     - DATEADD(day,-n) → now() - make_interval(days => n)
     - @parameter      → a plain named parameter
     - CAST(x AS DATE) → x::date

   And one that is not a syntax change at all: the WHERE clause below
   matches 'Captured' exactly. On SQL Server the same clause also matched
   'captured' and 'CAPTURED' because of the collation. So this function
   returns FEWER rows than the procedure it replaces, and it does so
   silently. That is the migration bug that costs money, and no
   type-mapping table would have caught it.                             */

CREATE OR REPLACE FUNCTION daily_settlement_summary(days_back integer DEFAULT 7)
RETURNS TABLE (
    merchant_id  integer,
    legal_name   text,
    capture_date date,
    txn_count    bigint,
    gross_amount numeric,
    total_fees   numeric,
    net_amount   numeric
)
LANGUAGE plpgsql
STABLE
AS $$
BEGIN
    RETURN QUERY
    SELECT
        m.merchant_id,
        m.legal_name,
        t.captured_at::date,
        COUNT(*),
        SUM(t.amount),
        SUM(COALESCE(t.fee_amount, 0)),
        SUM(t.amount - COALESCE(t.fee_amount, 0))
    FROM transactions t
    JOIN merchants m ON m.merchant_id = t.merchant_id
    WHERE t.captured_at >= now() - make_interval(days => days_back)
      AND t.txn_status = 'Captured'
    GROUP BY m.merchant_id, m.legal_name, t.captured_at::date
    ORDER BY 3 DESC, 5 DESC;
END;
$$;

/* ─── least privilege ─────────────────────────────────────────────── */

/* The application never connects as the master user. Two roles, split
   by what they are allowed to do, which is what a compliance auditor
   asks to see. */

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'app_rw') THEN
        CREATE ROLE app_rw NOLOGIN;
    END IF;
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'app_ro') THEN
        CREATE ROLE app_ro NOLOGIN;
    END IF;
END
$$;

GRANT USAGE ON SCHEMA public TO app_rw, app_ro;

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO app_rw;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO app_rw;

GRANT SELECT ON ALL TABLES IN SCHEMA public TO app_ro;

-- Applies to tables created later too, so a new table does not silently
-- become invisible to the read-only role.
ALTER DEFAULT PRIVILEGES IN SCHEMA public
    GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO app_rw;
ALTER DEFAULT PRIVILEGES IN SCHEMA public
    GRANT SELECT ON TABLES TO app_ro;
